version: '3.1'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "62312:3000"
    depends_on:
      - mongodb
    restart: always
    volumes:
      - metabase-data:/metabase-data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: metabase
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env

volumes:
  metabase-data:
  mongodb-data:
